# Creating 1D array

### Method 1:

In [1]:
import numpy as np

In [4]:
a = [1,2,3,4,5]
arr_1 = np.array(a)

print("List -->", a)
print("NumPy array -->", arr_1)

List --> [1, 2, 3, 4, 5]
NumPy array --> [1 2 3 4 5]


### Method 2:

In [5]:
array_2 = np.array ([1,2,3,4,5])
print(array_2)

[1 2 3 4 5]


### Method 3:

In [9]:
# Take value from user

a = []
print()
lenght = int(input("Enter the length of array: "))
for i in range(lenght):
    value = int(input("Enter the value of array: "))
    a.append(value)

arr_3 = np.array(a)
print(arr_3)


Enter the length of array: 2
Enter the value of array: 2
Enter the value of array: 2
[2 2]


In [23]:
print("Dimension of the array is ", arr_3.ndim)
print("Shape of the array is ", arr_3.shape)

Dimension of the array is  1
Shape of the array is  (2,)


# Creating 2D array

In [10]:
arr_4 = np.array([[1,2,3],[4,5,6]])
print(arr_4)

[[1 2 3]
 [4 5 6]]


In [21]:
# Take value from user

matrix = []
row = int(input("Enter the number of row: "))
col = int(input("Enter the number of column: "))

for i in range(row):
    a = []
    for j in range(col):
        value = int(input("Enter the value: "))
        a.append(value)
        
    matrix.append(a)

arr_5 = np.array(matrix)
print(arr_5)
print("\n")

print(matrix[0])
print(matrix[1])
print(matrix[0][0])
print(matrix[1][0])

Enter the number of row: 2
Enter the number of column: 3
Enter the value: 1
Enter the value: 2
Enter the value: 3
Enter the value: 4
Enter the value: 5
Enter the value: 6
[[1 2 3]
 [4 5 6]]


[1, 2, 3]
[4, 5, 6]
1
4


In [24]:
print("Dimension of the array is ", arr_5.ndim)
print("Shape of the array is ", arr_5.shape)

Dimension of the array is  2
Shape of the array is  (2, 3)
