In [1]:
import numpy as np


In [9]:
#Creating one dimensional array

li = [1,2,3,4,5]
n1 = np.array(li)
n1

array([1, 2, 3, 4, 5])

In [6]:
type (n1)

numpy.ndarray

In [7]:
n2 = np.array([6,7,8,9])

In [8]:
n2

array([6, 7, 8, 9])

In [15]:
#Creating multi-dimensional array

li2 = [1,3,5,7,9]
li3 = [2,4,6,8,10]

n3 = np.array([li2,li3])
n3

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [14]:

type (n3)

numpy.ndarray

In [13]:
#Initializing NumPy with zeros

#syntex: n = np.zeros ((row,col))

n = np.zeros((2,3))
n1 = np.zeros((5,5))

In [7]:

n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#Initializing NumPy array with a number

#syntex: n = np.zeros ((row,col),number)

n3 = np.full((4,5),9)

In [9]:
n3

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [16]:
#Initializing NumPy array with a range

n = np.arange(10,20)

In [11]:
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
n2 = np.arange(10,30,2)

In [17]:
n2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
#Initializing NumPy array with random number

#syntex: n = np.random.randint(start,end,how many numbers we want)

n3 = np.random.randint(1,100,7)

In [25]:
n3

array([89, 83, 73, 14, 61, 87, 82])

In [28]:
#Checking the shape (Number of row column) of NumPy array

n4 = np.array([[1,2,3,4],[5,6,7,8]])


In [29]:
n4.shape


(2, 4)

In [32]:
n4.shape = (4,2)

In [33]:
n4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
n4.shape = (8,1)

In [35]:
n4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [2]:
#Joining NumPy array
#vstack --> vertical stack
#hstack --> horizontal stack
#column_stack

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [5]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
#NumPy intersection and difference

n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])



In [7]:
np.intersect1d(n1,n2)

array([50, 60])

In [8]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [9]:
np.setdiff1d(n2,n1)

array([70, 80, 90])