# 1D NumPy array basic operation

In [2]:
import numpy as np

In [10]:
#Creating NumPy array

arr_1 = np.array([1,2,3,4,5,6,7])
arr_2 = np.array([1,-2,3,-4,5,-6,7])

print(arr_2)
print(arr_1)

[ 1 -2  3 -4  5 -6  7]
[1 2 3 4 5 6 7]


In [13]:
# Array addition (This the addion of each element of same index of the two array and this is not matrix addition)

arr_add = arr_1 + arr_2
print(arr_add)

[ 2  0  6  0 10  0 14]


In [14]:
arr_sub = arr_1 - arr_2

print(arr_sub)

[ 0  4  0  8  0 12  0]


In [17]:
# Array multiplication is not as like the matrix multiplication

arr_mul = arr_1 * arr_2
print(arr_mul)

[  1  -4   9 -16  25 -36  49]


In [18]:
arr_div = arr_1 / arr_2
print(arr_div)

[ 1. -1.  1. -1.  1. -1.  1.]


# 2D NumPy array operation

In [22]:
arr_3 = np.array([[1,2,3],[4,5,6]])
print(arr_3)

[[1 2 3]
 [4 5 6]]


In [23]:
arr_4 = np.array([[1,2,3],[4,5,6]])
print(arr_4)

[[1 2 3]
 [4 5 6]]


In [25]:
# Addition of 2D array

arr_add = np.add(arr_3,arr_4)
print(arr_add)

[[ 2  4  6]
 [ 8 10 12]]


In [26]:
# Multiplication of 2D array (This is not same as the multiplication of matrix)

arr_mul = np.multiply(arr_3, arr_4)
print(arr_mul)

[[ 1  4  9]
 [16 25 36]]


In [28]:
arr_div = np.divide(arr_3, arr_4)
print(arr_div)

[[1. 1. 1.]
 [1. 1. 1.]]


## Matrix multiplication of 2D array

In [29]:
arr_mat_mul = np.matmul(arr_3, arr_4)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [30]:
# For performing the matrix multiplication column of first matrix should be equal to row of second matrix

In [32]:
arr_5 = np.array([[1,2,3],[4,5,6]])
arr_6 = np.array([[7,8],[9,10],[11,12]])

print(arr_5)
print("\n")
print(arr_6)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]


In [33]:
arr_mat_mul = np.matmul(arr_5, arr_6)
print(arr_mat_mul)

[[ 58  64]
 [139 154]]
