In [1]:
import numpy as np

In [12]:
arr_1 = np.random.randint(1,100,12)   # random.randint(1,100,12) create 12 random integer number between 1 to 100
print(arr_1)
print(type(arr_1))
print(arr_1.shape)
print(arr_1.ndim)

[61 21 68 25 85  6 99 97 63 33 59 11]
<class 'numpy.ndarray'>
(12,)
1


### <b> converting 1D array into 2D array

In [21]:
arr_2 = arr_1.reshape(2,6)
print(arr_2)
print("Shape of this array is (row,column) = ",arr_2.shape)
print("\n")

arr_3 = arr_1.reshape(3,4)
print(arr_3)
print("Shape of this array is (row,column) = ",arr_3.shape)
print("\n")

arr_4 = arr_1.reshape(4,3)
print(arr_4)
print("Shape of this array is (row,column) = ",arr_4.shape)
print("\n")

arr_5 = arr_1.reshape(6,2)
print(arr_5)
print("Shape of this array is (row,column) = ",arr_5.shape)

[[61 21 68 25 85  6]
 [99 97 63 33 59 11]]
Shape of this array is (row,column) =  (2, 6)


[[61 21 68 25]
 [85  6 99 97]
 [63 33 59 11]]
Shape of this array is (row,column) =  (3, 4)


[[61 21 68]
 [25 85  6]
 [99 97 63]
 [33 59 11]]
Shape of this array is (row,column) =  (4, 3)


[[61 21]
 [68 25]
 [85  6]
 [99 97]
 [63 33]
 [59 11]]
Shape of this array is (row,column) =  (6, 2)


### Converting 2D array into 1D array

In [24]:
arr_6 = arr_2.reshape(12)
print(arr_6)
print("Shape of this array is (number of element) = ", arr_6.shape)

[61 21 68 25 85  6 99 97 63 33 59 11]
Shape of this array is (row,column)=  (12,)


In [26]:
arr_7 = arr_3.reshape(12)
print(arr_7)
print("Shape of this array is (number of element) = ", arr_7.shape)

[61 21 68 25 85  6 99 97 63 33 59 11]
Shape of this array is (number of element) =  (12,)


In [27]:
arr_8 = arr_4.reshape(12)
print(arr_8)
print("Shape of this array is (number of element) = ", arr_8.shape)

[61 21 68 25 85  6 99 97 63 33 59 11]
Shape of this array is (number of element) =  (12,)


In [25]:
arr_9 = arr_5.reshape(12)
print(arr_6)
print("Shape of this array is (number of element) = ", arr_9.shape)

[61 21 68 25 85  6 99 97 63 33 59 11]
Shape of this array is (number of element) =  (12,)
